In [264]:
import pandas as pd
import numpy as np

In [265]:
df = pd.read_csv("NIGERIA_WFP_ADMIN1.csv", sep=None, engine="python")
df["time"] = pd.to_datetime(df["time"], errors="coerce", dayfirst=True)
df = df.dropna(subset=["time", "NAME_1"])
df["year"] = df["time"].dt.year

# NDVI: prends celui que tu as (vim)
df["ndvi"] = df["vim"]

# On filtre la qualité NDVI
df = df[df["viq"] >= 80].copy()   

df = df.sort_values(["NAME_1", "time"])
df.head(5)

,time,NAME_1,inadequate,bnds,Y,X,Evap_tavg,LWdown_f_tavg,Lwnet_tavg,Psurf_f_tavg,...,SoilMoi40_100cm_tavg,SoilMoi100_200cm_tavg,SoilTemp00_10cm_tavg,SoilTemp10_40cm_tavg,SoilTemp40_100cm_tavg,SoilTemp100_200cm_tavg,vim,viq,year,ndvi
0,2023-01-01,Abia,0.296774,0.5,5.395,7.471889,0.000016,385.566324,-71.064699,99941.271400,...,0.374807,0.389133,300.138219,299.605325,299.121555,298.700373,0.569790,101.510920,2023,0.569790
28,2023-01-02,Abia,0.401515,0.5,5.395,7.471889,0.000014,392.934595,-69.757725,99864.297600,...,0.365446,0.375858,301.087698,300.549694,300.019129,299.368246,0.598635,100.312830,2023,0.598635
56,2023-01-03,Abia,0.281046,0.5,5.395,7.471889,0.000026,408.719824,-44.999965,99913.329933,...,0.379434,0.378395,299.624543,299.767199,299.874593,299.740318,0.683211,102.223080,2023,0.683211
84,2023-01-04,Abia,0.300613,0.5,5.395,7.471889,0.000030,416.609924,-39.776577,99798.052400,...,0.396723,0.403678,299.950588,299.849166,299.700418,299.525405,0.751135,102.335600,2023,0.751135
112,2023-01-05,Abia,0.226667,0.5,5.395,7.471889,0.000039,419.145751,-35.249339,99990.250067,...,0.413261,0.422155,299.604193,299.639713,299.624382,299.501924,0.790905,102.097565,2023,0.790905

In [266]:
df["month"] = df["time"].astype(str).str.split("-").str[2].astype(int)
df["year"]  = df["time"].astype(str).str.split("-").str[0].astype(int)

df.head(5)

,time,NAME_1,inadequate,bnds,Y,X,Evap_tavg,LWdown_f_tavg,Lwnet_tavg,Psurf_f_tavg,...,SoilMoi100_200cm_tavg,SoilTemp00_10cm_tavg,SoilTemp10_40cm_tavg,SoilTemp40_100cm_tavg,SoilTemp100_200cm_tavg,vim,viq,year,ndvi,month
0,2023-01-01,Abia,0.296774,0.5,5.395,7.471889,0.000016,385.566324,-71.064699,99941.271400,...,0.389133,300.138219,299.605325,299.121555,298.700373,0.569790,101.510920,2023,0.569790,1
28,2023-01-02,Abia,0.401515,0.5,5.395,7.471889,0.000014,392.934595,-69.757725,99864.297600,...,0.375858,301.087698,300.549694,300.019129,299.368246,0.598635,100.312830,2023,0.598635,2
56,2023-01-03,Abia,0.281046,0.5,5.395,7.471889,0.000026,408.719824,-44.999965,99913.329933,...,0.378395,299.624543,299.767199,299.874593,299.740318,0.683211,102.223080,2023,0.683211,3
84,2023-01-04,Abia,0.300613,0.5,5.395,7.471889,0.000030,416.609924,-39.776577,99798.052400,...,0.403678,299.950588,299.849166,299.700418,299.525405,0.751135,102.335600,2023,0.751135,4
112,2023-01-05,Abia,0.226667,0.5,5.395,7.471889,0.000039,419.145751,-35.249339,99990.250067,...,0.422155,299.604193,299.639713,299.624382,299.501924,0.790905,102.097565,2023,0.790905,5

In [267]:
ndvi_monthly = (
    df.groupby(["NAME_1", "month"], as_index=False)
      .agg(ndvi_mean=("vim", "mean"),
           n_obs=("vim", "size"),
           inadequate=("inadequate","mean"))
      .sort_values(["NAME_1", "month"])
)

ndvi_monthly.head(20)

   NAME_1  month  ndvi_mean  n_obs  inadequate
0    Abia      1   0.561547      3    0.357967
1    Abia      2   0.597959      3    0.409660
2    Abia      3   0.678959      2    0.315020
3    Abia      4   0.742734      3    0.346308
4    Abia      5   0.780453      3    0.289423
5    Abia      6   0.797064      3    0.277903
6    Abia      7   0.796211      3    0.301968
7    Abia      8   0.800370      3    0.246360
8    Abia      9   0.811505      3    0.254307
9    Abia     10   0.794662      3    0.313025
10   Abia     11   0.726370      3    0.295682
11   Abia     12   0.633201      3    0.381811
12  Abuja      1   0.317709      3    0.272305
13  Abuja      2   0.292107      3    0.288947
14  Abuja      3   0.323778      2    0.312745
15  Abuja      4   0.418740      3    0.261846
16  Abuja      5   0.554993      3    0.244790
17  Abuja      6   0.669883      3    0.301232
18  Abuja      7   0.720420      3    0.321530
19  Abuja      8   0.727833      3    0.231547

In [268]:
ndvi_monthly["mean_admin"] = ndvi_monthly.groupby("NAME_1")["ndvi_mean"].transform("mean")
ndvi_monthly.head(20)

   NAME_1  month  ndvi_mean  n_obs  inadequate  mean_admin
0    Abia      1   0.561547      3    0.357967    0.726753
1    Abia      2   0.597959      3    0.409660    0.726753
2    Abia      3   0.678959      2    0.315020    0.726753
3    Abia      4   0.742734      3    0.346308    0.726753
4    Abia      5   0.780453      3    0.289423    0.726753
5    Abia      6   0.797064      3    0.277903    0.726753
6    Abia      7   0.796211      3    0.301968    0.726753
7    Abia      8   0.800370      3    0.246360    0.726753
8    Abia      9   0.811505      3    0.254307    0.726753
9    Abia     10   0.794662      3    0.313025    0.726753
10   Abia     11   0.726370      3    0.295682    0.726753
11   Abia     12   0.633201      3    0.381811    0.726753
12  Abuja      1   0.317709      3    0.272305    0.533885
13  Abuja      2   0.292107      3    0.288947    0.533885
14  Abuja      3   0.323778      2    0.312745    0.533885
15  Abuja      4   0.418740      3    0.261846    0.533885
16  Abuja      5   0.554993      3    0.244790    0.533885
17  Abuja      6   0.669883      3    0.301232    0.533885
18  Abuja      7   0.720420      3    0.321530    0.533885
19  Abuja      8   0.727833      3    0.231547    0.533885

In [269]:
ndvi_monthly["std_admin"] = ndvi_monthly.groupby("NAME_1")["ndvi_mean"].transform("std")
ndvi_monthly.head(20)

   NAME_1  month  ndvi_mean  n_obs  inadequate  mean_admin  std_admin
0    Abia      1   0.561547      3    0.357967    0.726753   0.087925
1    Abia      2   0.597959      3    0.409660    0.726753   0.087925
2    Abia      3   0.678959      2    0.315020    0.726753   0.087925
3    Abia      4   0.742734      3    0.346308    0.726753   0.087925
4    Abia      5   0.780453      3    0.289423    0.726753   0.087925
5    Abia      6   0.797064      3    0.277903    0.726753   0.087925
6    Abia      7   0.796211      3    0.301968    0.726753   0.087925
7    Abia      8   0.800370      3    0.246360    0.726753   0.087925
8    Abia      9   0.811505      3    0.254307    0.726753   0.087925
9    Abia     10   0.794662      3    0.313025    0.726753   0.087925
10   Abia     11   0.726370      3    0.295682    0.726753   0.087925
11   Abia     12   0.633201      3    0.381811    0.726753   0.087925
12  Abuja      1   0.317709      3    0.272305    0.533885   0.171904
13  Abuja      2   0.292107      3    0.288947    0.533885   0.171904
14  Abuja      3   0.323778      2    0.312745    0.533885   0.171904
15  Abuja      4   0.418740      3    0.261846    0.533885   0.171904
16  Abuja      5   0.554993      3    0.244790    0.533885   0.171904
17  Abuja      6   0.669883      3    0.301232    0.533885   0.171904
18  Abuja      7   0.720420      3    0.321530    0.533885   0.171904
19  Abuja      8   0.727833      3    0.231547    0.533885   0.171904

In [270]:
ndvi_monthly["ndvi_anomaly"] = ((ndvi_monthly["ndvi_mean"]-ndvi_monthly["mean_admin"])/ndvi_monthly["std_admin"])

ndvi_monthly.head(20)

,NAME_1,month,ndvi_mean,n_obs,inadequate,mean_admin,std_admin,ndvi_anomaly
0,Abia,1,0.561547,3,0.357967,0.726753,0.087925,-1.878941
1,Abia,2,0.597959,3,0.409660,0.726753,0.087925,-1.464822
2,Abia,3,0.678959,2,0.315020,0.726753,0.087925,-0.543580
3,Abia,4,0.742734,3,0.346308,0.726753,0.087925,0.181765
4,Abia,5,0.780453,3,0.289423,0.726753,0.087925,0.610754
5,Abia,6,0.797064,3,0.277903,0.726753,0.087925,0.799669
6,Abia,7,0.796211,3,0.301968,0.726753,0.087925,0.789975
7,Abia,8,0.800370,3,0.246360,0.726753,0.087925,0.837270
8,Abia,9,0.811505,3,0.254307,0.726753,0.087925,0.963916
9,Abia,10,0.794662,3,0.313025,0.726753,0.087925,0.772354
10,Abia,11,0.726370,3,0.295682,0.726753,0.087925,-0.004356
11,Abia,12,0.633201,3,0.381811,0.726753,0.087925,-1.064004
12,Abuja,1,0.317709,3,0.272305,0.533885,0.171904,-1.257538
13,Abuja,2,0.292107,3,0.288947,0.533885,0.171904,-1.406470
14,Abuja,3,0.323778,2,0.312745,0.533885,0.171904,-1.222234
15,Abuja,4,0.418740,3,0.261846,0.533885,0.171904,-0.669818
16,Abuja,5,0.554993,3,0.244790,0.533885,0.171904,0.122789
17,Abuja,6,0.669883,3,0.301232,0.533885,0.171904,0.791128
18,Abuja,7,0.720420,3,0.321530,0.533885,0.171904,1.085111
19,Abuja,8,0.727833,3,0.231547,0.533885,0.171904,1.128236

In [271]:
ndvi_monthly["mean_anomaly_admin"] = (ndvi_monthly.groupby("NAME_1")["ndvi_anomaly"].transform("mean"))
ndvi_monthly.head(20)

,NAME_1,month,ndvi_mean,n_obs,inadequate,mean_admin,std_admin,ndvi_anomaly,mean_anomaly_admin
0,Abia,1,0.561547,3,0.357967,0.726753,0.087925,-1.878941,-3.145632e-16
1,Abia,2,0.597959,3,0.409660,0.726753,0.087925,-1.464822,-3.145632e-16
2,Abia,3,0.678959,2,0.315020,0.726753,0.087925,-0.543580,-3.145632e-16
3,Abia,4,0.742734,3,0.346308,0.726753,0.087925,0.181765,-3.145632e-16
4,Abia,5,0.780453,3,0.289423,0.726753,0.087925,0.610754,-3.145632e-16
5,Abia,6,0.797064,3,0.277903,0.726753,0.087925,0.799669,-3.145632e-16
6,Abia,7,0.796211,3,0.301968,0.726753,0.087925,0.789975,-3.145632e-16
7,Abia,8,0.800370,3,0.246360,0.726753,0.087925,0.837270,-3.145632e-16
8,Abia,9,0.811505,3,0.254307,0.726753,0.087925,0.963916,-3.145632e-16
9,Abia,10,0.794662,3,0.313025,0.726753,0.087925,0.772354,-3.145632e-16
10,Abia,11,0.726370,3,0.295682,0.726753,0.087925,-0.004356,-3.145632e-16
11,Abia,12,0.633201,3,0.381811,0.726753,0.087925,-1.064004,-3.145632e-16
12,Abuja,1,0.317709,3,0.272305,0.533885,0.171904,-1.257538,-1.295260e-16
13,Abuja,2,0.292107,3,0.288947,0.533885,0.171904,-1.406470,-1.295260e-16
14,Abuja,3,0.323778,2,0.312745,0.533885,0.171904,-1.222234,-1.295260e-16
15,Abuja,4,0.418740,3,0.261846,0.533885,0.171904,-0.669818,-1.295260e-16
16,Abuja,5,0.554993,3,0.244790,0.533885,0.171904,0.122789,-1.295260e-16
17,Abuja,6,0.669883,3,0.301232,0.533885,0.171904,0.791128,-1.295260e-16
18,Abuja,7,0.720420,3,0.321530,0.533885,0.171904,1.085111,-1.295260e-16
19,Abuja,8,0.727833,3,0.231547,0.533885,0.171904,1.128236,-1.295260e-16

on remarque que faire la moyenne des anomalies n'est pas utile comme elle est égale à 0

In [272]:
q = 0.20  # 20e percentile

# seuil par Etat (répété sur chaque ligne de l'Etat)
ndvi_monthly["ndvi_q20_threshold"] = (
    ndvi_monthly.groupby("NAME_1")["ndvi_anomaly"]
    .transform(lambda s: s.quantile(q))
)

# indicateur NDVI bas
ndvi_monthly["ndvi_low_q20"] = ndvi_monthly["ndvi_anomaly"] < ndvi_monthly["ndvi_q20_threshold"]

ndvi_monthly.head(24)

,NAME_1,month,ndvi_mean,n_obs,inadequate,mean_admin,std_admin,ndvi_anomaly,mean_anomaly_admin,ndvi_q20_threshold,ndvi_low_q20
0,Abia,1,0.561547,3,0.357967,0.726753,0.087925,-1.878941,-3.145632e-16,-0.959919,True
1,Abia,2,0.597959,3,0.409660,0.726753,0.087925,-1.464822,-3.145632e-16,-0.959919,True
2,Abia,3,0.678959,2,0.315020,0.726753,0.087925,-0.543580,-3.145632e-16,-0.959919,False
3,Abia,4,0.742734,3,0.346308,0.726753,0.087925,0.181765,-3.145632e-16,-0.959919,False
4,Abia,5,0.780453,3,0.289423,0.726753,0.087925,0.610754,-3.145632e-16,-0.959919,False
5,Abia,6,0.797064,3,0.277903,0.726753,0.087925,0.799669,-3.145632e-16,-0.959919,False
6,Abia,7,0.796211,3,0.301968,0.726753,0.087925,0.789975,-3.145632e-16,-0.959919,False
7,Abia,8,0.800370,3,0.246360,0.726753,0.087925,0.837270,-3.145632e-16,-0.959919,False
8,Abia,9,0.811505,3,0.254307,0.726753,0.087925,0.963916,-3.145632e-16,-0.959919,False
9,Abia,10,0.794662,3,0.313025,0.726753,0.087925,0.772354,-3.145632e-16,-0.959919,False
10,Abia,11,0.726370,3,0.295682,0.726753,0.087925,-0.004356,-3.145632e-16,-0.959919,False
11,Abia,12,0.633201,3,0.381811,0.726753,0.087925,-1.064004,-3.145632e-16,-0.959919,True
12,Abuja,1,0.317709,3,0.272305,0.533885,0.171904,-1.257538,-1.295260e-16,-1.113462,True
13,Abuja,2,0.292107,3,0.288947,0.533885,0.171904,-1.406470,-1.295260e-16,-1.113462,True
14,Abuja,3,0.323778,2,0.312745,0.533885,0.171904,-1.222234,-1.295260e-16,-1.113462,True
15,Abuja,4,0.418740,3,0.261846,0.533885,0.171904,-0.669818,-1.295260e-16,-1.113462,False
16,Abuja,5,0.554993,3,0.244790,0.533885,0.171904,0.122789,-1.295260e-16,-1.113462,False
17,Abuja,6,0.669883,3,0.301232,0.533885,0.171904,0.791128,-1.295260e-16,-1.113462,False
18,Abuja,7,0.720420,3,0.321530,0.533885,0.171904,1.085111,-1.295260e-16,-1.113462,False
19,Abuja,8,0.727833,3,0.231547,0.533885,0.171904,1.128236,-1.295260e-16,-1.113462,False
20,Abuja,9,0.721758,3,0.251937,0.533885,0.171904,1.092894,-1.295260e-16,-1.113462,False
21,Abuja,10,0.680315,3,0.266468,0.533885,0.171904,0.851810,-1.295260e-16,-1.113462,False
22,Abuja,11,0.561814,3,0.340850,0.533885,0.171904,0.162467,-1.295260e-16,-1.113462,False
23,Abuja,12,0.417270,3,0.350091,0.533885,0.171904,-0.678375,-1.295260e-16,-1.113462,False

In [273]:
spi_df = pd.read_csv("SPI.csv", sep=None, engine="python")
print(spi_df.columns)
spi_df.head(20)

Index(['﻿', 'State', 'month', 'SPI_Cum1', 'SPI_Cum3', 'SPI_Cum6', 'year'], dtype='object')

     ﻿    State  month  SPI_Cum1  SPI_Cum3  SPI_Cum6  year
0    1     Abia      1   -0.6910   -0.5510   -1.9670  2023
1    2     Abia      2   -1.8340   -1.2190   -1.9820  2023
2    3     Abia      3    0.7490   -0.1740   -0.3740  2023
3    4     Abia      4   -0.0510   -0.0190   -0.3940  2023
4    5     Abia      5   -0.2950    0.0200   -0.3890  2023
5    6     Abia      6    1.3650    0.7390    0.5660  2023
6    7     Abia      7   -0.4620    0.3660    0.3020  2023
7    8     Abia      8   -1.8340   -0.8400   -0.8480  2023
8    9     Abia      9   -0.0660   -1.7480   -1.0120  2023
9   10     Abia     10   -0.2890   -2.1500   -0.9520  2023
10  11     Abia     11   -0.2520   -0.4020   -0.8900  2023
11  12     Abia     12   -0.8420   -0.5740   -1.6320  2023
12  13  Adamawa      1    0.6350    0.0135   -0.1195  2023
13  14  Adamawa      2   -1.1110    0.5295    0.2720  2023
14  15  Adamawa      3    0.7525    0.7360   -1.7440  2023
15  16  Adamawa      4    0.0890    0.1200    0.0750  2023
16  17  Adamawa      5   -0.2875   -0.2555   -0.2690  2023
17  18  Adamawa      6    0.8315    0.2260    0.2215  2023
18  19  Adamawa      7   -1.2205   -0.5665   -0.5390  2023
19  20  Adamawa      8   -0.6340   -0.6525   -0.7505  2023

In [274]:
spi_df = spi_df.rename(columns={"State": "NAME_1"})

In [275]:

spi_monthly = (
    spi_df.groupby(["NAME_1", "month"], as_index=False)
      .agg(spi_mean=("SPI_Cum1", "mean"),
           n_obs=("SPI_Cum1", "size"))
      .sort_values(["NAME_1", "month"])
)
spi_monthly.head(20)

   NAME_1  month  spi_mean  n_obs
0    Abia      1 -0.329000      3
1    Abia      2 -1.373667      3
2    Abia      3 -0.002333      3
3    Abia      4  0.445333      3
4    Abia      5 -1.099000      3
5    Abia      6 -0.363000      3
6    Abia      7 -0.521000      3
7    Abia      8 -1.828667      3
8    Abia      9 -0.670667      3
9    Abia     10 -1.220333      3
10   Abia     11 -0.653333      3
11   Abia     12 -0.180333      3
12  Abuja      1 -0.159333      3
13  Abuja      2  0.666667      3
14  Abuja      3  0.047167      3
15  Abuja      4 -0.276583      3
16  Abuja      5 -0.688167      3
17  Abuja      6 -0.418667      3
18  Abuja      7 -0.612083      3
19  Abuja      8 -0.963500      3

In [276]:
spi_monthly["mean_spi_admin"] = spi_monthly.groupby("NAME_1")["spi_mean"].transform("mean")
spi_monthly.head(20)

   NAME_1  month  spi_mean  n_obs  mean_spi_admin
0    Abia      1 -0.329000      3       -0.649667
1    Abia      2 -1.373667      3       -0.649667
2    Abia      3 -0.002333      3       -0.649667
3    Abia      4  0.445333      3       -0.649667
4    Abia      5 -1.099000      3       -0.649667
5    Abia      6 -0.363000      3       -0.649667
6    Abia      7 -0.521000      3       -0.649667
7    Abia      8 -1.828667      3       -0.649667
8    Abia      9 -0.670667      3       -0.649667
9    Abia     10 -1.220333      3       -0.649667
10   Abia     11 -0.653333      3       -0.649667
11   Abia     12 -0.180333      3       -0.649667
12  Abuja      1 -0.159333      3       -0.295083
13  Abuja      2  0.666667      3       -0.295083
14  Abuja      3  0.047167      3       -0.295083
15  Abuja      4 -0.276583      3       -0.295083
16  Abuja      5 -0.688167      3       -0.295083
17  Abuja      6 -0.418667      3       -0.295083
18  Abuja      7 -0.612083      3       -0.295083
19  Abuja      8 -0.963500      3       -0.295083

In [277]:
spi_monthly["std_spi_admin"] = spi_monthly.groupby("NAME_1")["spi_mean"].transform("std")
spi_monthly.head(20)

   NAME_1  month  spi_mean  n_obs  mean_spi_admin  std_spi_admin
0    Abia      1 -0.329000      3       -0.649667       0.638331
1    Abia      2 -1.373667      3       -0.649667       0.638331
2    Abia      3 -0.002333      3       -0.649667       0.638331
3    Abia      4  0.445333      3       -0.649667       0.638331
4    Abia      5 -1.099000      3       -0.649667       0.638331
5    Abia      6 -0.363000      3       -0.649667       0.638331
6    Abia      7 -0.521000      3       -0.649667       0.638331
7    Abia      8 -1.828667      3       -0.649667       0.638331
8    Abia      9 -0.670667      3       -0.649667       0.638331
9    Abia     10 -1.220333      3       -0.649667       0.638331
10   Abia     11 -0.653333      3       -0.649667       0.638331
11   Abia     12 -0.180333      3       -0.649667       0.638331
12  Abuja      1 -0.159333      3       -0.295083       0.509597
13  Abuja      2  0.666667      3       -0.295083       0.509597
14  Abuja      3  0.047167      3       -0.295083       0.509597
15  Abuja      4 -0.276583      3       -0.295083       0.509597
16  Abuja      5 -0.688167      3       -0.295083       0.509597
17  Abuja      6 -0.418667      3       -0.295083       0.509597
18  Abuja      7 -0.612083      3       -0.295083       0.509597
19  Abuja      8 -0.963500      3       -0.295083       0.509597

In [278]:
spi_monthly["spi_anomaly"] = ((spi_monthly["spi_mean"]-spi_monthly["mean_spi_admin"])/spi_monthly["std_spi_admin"])

spi_monthly.head(20)

   NAME_1  month  spi_mean  n_obs  mean_spi_admin  std_spi_admin  spi_anomaly
0    Abia      1 -0.329000      3       -0.649667       0.638331     0.502352
1    Abia      2 -1.373667      3       -0.649667       0.638331    -1.134208
2    Abia      3 -0.002333      3       -0.649667       0.638331     1.014103
3    Abia      4  0.445333      3       -0.649667       0.638331     1.715411
4    Abia      5 -1.099000      3       -0.649667       0.638331    -0.703919
5    Abia      6 -0.363000      3       -0.649667       0.638331     0.449088
6    Abia      7 -0.521000      3       -0.649667       0.638331     0.201567
7    Abia      8 -1.828667      3       -0.649667       0.638331    -1.847004
8    Abia      9 -0.670667      3       -0.649667       0.638331    -0.032898
9    Abia     10 -1.220333      3       -0.649667       0.638331    -0.893998
10   Abia     11 -0.653333      3       -0.649667       0.638331    -0.005744
11   Abia     12 -0.180333      3       -0.649667       0.638331     0.735251
12  Abuja      1 -0.159333      3       -0.295083       0.509597     0.266387
13  Abuja      2  0.666667      3       -0.295083       0.509597     1.887275
14  Abuja      3  0.047167      3       -0.295083       0.509597     0.671609
15  Abuja      4 -0.276583      3       -0.295083       0.509597     0.036303
16  Abuja      5 -0.688167      3       -0.295083       0.509597    -0.771361
17  Abuja      6 -0.418667      3       -0.295083       0.509597    -0.242512
18  Abuja      7 -0.612083      3       -0.295083       0.509597    -0.622060
19  Abuja      8 -0.963500      3       -0.295083       0.509597    -1.311657

In [279]:
spi_monthly2 = spi_monthly.copy(deep=True) #copier df pour faire les lags par la suite

In [280]:
q = 0.20  # 20e percentile

# seuil par Etat (répété sur chaque ligne de l'Etat)
spi_monthly["spi_q20_threshold"] = (
    spi_monthly.groupby("NAME_1")["spi_anomaly"]
    .transform(lambda s: s.quantile(q))
)

# indicateur SPI bas
spi_monthly["spi_low_q20"] = spi_monthly["spi_anomaly"] < spi_monthly["spi_q20_threshold"]

spi_monthly.head(24)

,NAME_1,month,spi_mean,n_obs,mean_spi_admin,std_spi_admin,spi_anomaly,spi_q20_threshold,spi_low_q20
0,Abia,1,-0.329000,3,-0.649667,0.638331,0.502352,-0.855982,False
1,Abia,2,-1.373667,3,-0.649667,0.638331,-1.134208,-0.855982,True
2,Abia,3,-0.002333,3,-0.649667,0.638331,1.014103,-0.855982,False
3,Abia,4,0.445333,3,-0.649667,0.638331,1.715411,-0.855982,False
4,Abia,5,-1.099000,3,-0.649667,0.638331,-0.703919,-0.855982,False
5,Abia,6,-0.363000,3,-0.649667,0.638331,0.449088,-0.855982,False
6,Abia,7,-0.521000,3,-0.649667,0.638331,0.201567,-0.855982,False
7,Abia,8,-1.828667,3,-0.649667,0.638331,-1.847004,-0.855982,True
8,Abia,9,-0.670667,3,-0.649667,0.638331,-0.032898,-0.855982,False
9,Abia,10,-1.220333,3,-0.649667,0.638331,-0.893998,-0.855982,True
10,Abia,11,-0.653333,3,-0.649667,0.638331,-0.005744,-0.855982,False
11,Abia,12,-0.180333,3,-0.649667,0.638331,0.735251,-0.855982,False
12,Abuja,1,-0.159333,3,-0.295083,0.509597,0.266387,-0.741501,False
13,Abuja,2,0.666667,3,-0.295083,0.509597,1.887275,-0.741501,False
14,Abuja,3,0.047167,3,-0.295083,0.509597,0.671609,-0.741501,False
15,Abuja,4,-0.276583,3,-0.295083,0.509597,0.036303,-0.741501,False
16,Abuja,5,-0.688167,3,-0.295083,0.509597,-0.771361,-0.741501,True
17,Abuja,6,-0.418667,3,-0.295083,0.509597,-0.242512,-0.741501,False
18,Abuja,7,-0.612083,3,-0.295083,0.509597,-0.622060,-0.741501,False
19,Abuja,8,-0.963500,3,-0.295083,0.509597,-1.311657,-0.741501,True
20,Abuja,9,-1.172833,3,-0.295083,0.509597,-1.722439,-0.741501,True
21,Abuja,10,-0.112667,3,-0.295083,0.509597,0.357963,-0.741501,False
22,Abuja,11,0.044917,3,-0.295083,0.509597,0.667194,-0.741501,False
23,Abuja,12,0.104083,3,-0.295083,0.509597,0.783299,-0.741501,False

In [281]:
spi_lean2 = sorted(spi_monthly.loc[spi_monthly["spi_low_q20"] == True, "month"].unique())
spi_lean2

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12)]

In [282]:
q2 = 0.80  # 80e percentile

# seuil par Etat (répété sur chaque ligne de l'Etat)
spi_monthly2["spi_q80_threshold"] = (
    spi_monthly2.groupby("NAME_1")["spi_anomaly"]
    .transform(lambda s: s.quantile(q2))
)

# indicateur SPI haut
spi_monthly2["spi_high_q80"] = spi_monthly2["spi_anomaly"] > spi_monthly2["spi_q80_threshold"]

spi_monthly2.head(24)

,NAME_1,month,spi_mean,n_obs,mean_spi_admin,std_spi_admin,spi_anomaly,spi_q80_threshold,spi_high_q80
0,Abia,1,-0.329000,3,-0.649667,0.638331,0.502352,0.688671,False
1,Abia,2,-1.373667,3,-0.649667,0.638331,-1.134208,0.688671,False
2,Abia,3,-0.002333,3,-0.649667,0.638331,1.014103,0.688671,True
3,Abia,4,0.445333,3,-0.649667,0.638331,1.715411,0.688671,True
4,Abia,5,-1.099000,3,-0.649667,0.638331,-0.703919,0.688671,False
5,Abia,6,-0.363000,3,-0.649667,0.638331,0.449088,0.688671,False
6,Abia,7,-0.521000,3,-0.649667,0.638331,0.201567,0.688671,False
7,Abia,8,-1.828667,3,-0.649667,0.638331,-1.847004,0.688671,False
8,Abia,9,-0.670667,3,-0.649667,0.638331,-0.032898,0.688671,False
9,Abia,10,-1.220333,3,-0.649667,0.638331,-0.893998,0.688671,False
10,Abia,11,-0.653333,3,-0.649667,0.638331,-0.005744,0.688671,False
11,Abia,12,-0.180333,3,-0.649667,0.638331,0.735251,0.688671,True
12,Abuja,1,-0.159333,3,-0.295083,0.509597,0.266387,0.670726,False
13,Abuja,2,0.666667,3,-0.295083,0.509597,1.887275,0.670726,True
14,Abuja,3,0.047167,3,-0.295083,0.509597,0.671609,0.670726,True
15,Abuja,4,-0.276583,3,-0.295083,0.509597,0.036303,0.670726,False
16,Abuja,5,-0.688167,3,-0.295083,0.509597,-0.771361,0.670726,False
17,Abuja,6,-0.418667,3,-0.295083,0.509597,-0.242512,0.670726,False
18,Abuja,7,-0.612083,3,-0.295083,0.509597,-0.622060,0.670726,False
19,Abuja,8,-0.963500,3,-0.295083,0.509597,-1.311657,0.670726,False
20,Abuja,9,-1.172833,3,-0.295083,0.509597,-1.722439,0.670726,False
21,Abuja,10,-0.112667,3,-0.295083,0.509597,0.357963,0.670726,False
22,Abuja,11,0.044917,3,-0.295083,0.509597,0.667194,0.670726,False
23,Abuja,12,0.104083,3,-0.295083,0.509597,0.783299,0.670726,True

In [283]:
spi_lean3 = sorted(spi_monthly2.loc[spi_monthly2["spi_high_q80"] == True, "month"].unique())
spi_lean3

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12)]

In [284]:
spi_monthly2.groupby("NAME_1")["spi_high_q80"].mean().describe()

count    37.000000
mean      0.231982
std       0.034778
min       0.166667
25%       0.250000
50%       0.250000
75%       0.250000
max       0.250000
Name: spi_high_q80, dtype: float64

In [285]:
panel = ndvi_monthly.merge(
    spi_monthly[["NAME_1","month","spi_mean","spi_anomaly","spi_q20_threshold","spi_low_q20"]],
    on=["NAME_1","month"],
    how="left"
)

panel.head(20)

,NAME_1,month,ndvi_mean,n_obs,inadequate,mean_admin,std_admin,ndvi_anomaly,mean_anomaly_admin,ndvi_q20_threshold,ndvi_low_q20,spi_mean,spi_anomaly,spi_q20_threshold,spi_low_q20
0,Abia,1,0.561547,3,0.357967,0.726753,0.087925,-1.878941,-3.145632e-16,-0.959919,True,-0.329000,0.502352,-0.855982,False
1,Abia,2,0.597959,3,0.409660,0.726753,0.087925,-1.464822,-3.145632e-16,-0.959919,True,-1.373667,-1.134208,-0.855982,True
2,Abia,3,0.678959,2,0.315020,0.726753,0.087925,-0.543580,-3.145632e-16,-0.959919,False,-0.002333,1.014103,-0.855982,False
3,Abia,4,0.742734,3,0.346308,0.726753,0.087925,0.181765,-3.145632e-16,-0.959919,False,0.445333,1.715411,-0.855982,False
4,Abia,5,0.780453,3,0.289423,0.726753,0.087925,0.610754,-3.145632e-16,-0.959919,False,-1.099000,-0.703919,-0.855982,False
5,Abia,6,0.797064,3,0.277903,0.726753,0.087925,0.799669,-3.145632e-16,-0.959919,False,-0.363000,0.449088,-0.855982,False
6,Abia,7,0.796211,3,0.301968,0.726753,0.087925,0.789975,-3.145632e-16,-0.959919,False,-0.521000,0.201567,-0.855982,False
7,Abia,8,0.800370,3,0.246360,0.726753,0.087925,0.837270,-3.145632e-16,-0.959919,False,-1.828667,-1.847004,-0.855982,True
8,Abia,9,0.811505,3,0.254307,0.726753,0.087925,0.963916,-3.145632e-16,-0.959919,False,-0.670667,-0.032898,-0.855982,False
9,Abia,10,0.794662,3,0.313025,0.726753,0.087925,0.772354,-3.145632e-16,-0.959919,False,-1.220333,-0.893998,-0.855982,True
10,Abia,11,0.726370,3,0.295682,0.726753,0.087925,-0.004356,-3.145632e-16,-0.959919,False,-0.653333,-0.005744,-0.855982,False
11,Abia,12,0.633201,3,0.381811,0.726753,0.087925,-1.064004,-3.145632e-16,-0.959919,True,-0.180333,0.735251,-0.855982,False
12,Abuja,1,0.317709,3,0.272305,0.533885,0.171904,-1.257538,-1.295260e-16,-1.113462,True,-0.159333,0.266387,-0.741501,False
13,Abuja,2,0.292107,3,0.288947,0.533885,0.171904,-1.406470,-1.295260e-16,-1.113462,True,0.666667,1.887275,-0.741501,False
14,Abuja,3,0.323778,2,0.312745,0.533885,0.171904,-1.222234,-1.295260e-16,-1.113462,True,0.047167,0.671609,-0.741501,False
15,Abuja,4,0.418740,3,0.261846,0.533885,0.171904,-0.669818,-1.295260e-16,-1.113462,False,-0.276583,0.036303,-0.741501,False
16,Abuja,5,0.554993,3,0.244790,0.533885,0.171904,0.122789,-1.295260e-16,-1.113462,False,-0.688167,-0.771361,-0.741501,True
17,Abuja,6,0.669883,3,0.301232,0.533885,0.171904,0.791128,-1.295260e-16,-1.113462,False,-0.418667,-0.242512,-0.741501,False
18,Abuja,7,0.720420,3,0.321530,0.533885,0.171904,1.085111,-1.295260e-16,-1.113462,False,-0.612083,-0.622060,-0.741501,False
19,Abuja,8,0.727833,3,0.231547,0.533885,0.171904,1.128236,-1.295260e-16,-1.113462,False,-0.963500,-1.311657,-0.741501,True

In [286]:
panel["lean_risk"] = (panel["ndvi_low_q20"] & panel["spi_low_q20"]).astype(int)

panel.head(20)

,NAME_1,month,ndvi_mean,n_obs,inadequate,mean_admin,std_admin,ndvi_anomaly,mean_anomaly_admin,ndvi_q20_threshold,ndvi_low_q20,spi_mean,spi_anomaly,spi_q20_threshold,spi_low_q20,lean_risk
0,Abia,1,0.561547,3,0.357967,0.726753,0.087925,-1.878941,-3.145632e-16,-0.959919,True,-0.329000,0.502352,-0.855982,False,0
1,Abia,2,0.597959,3,0.409660,0.726753,0.087925,-1.464822,-3.145632e-16,-0.959919,True,-1.373667,-1.134208,-0.855982,True,1
2,Abia,3,0.678959,2,0.315020,0.726753,0.087925,-0.543580,-3.145632e-16,-0.959919,False,-0.002333,1.014103,-0.855982,False,0
3,Abia,4,0.742734,3,0.346308,0.726753,0.087925,0.181765,-3.145632e-16,-0.959919,False,0.445333,1.715411,-0.855982,False,0
4,Abia,5,0.780453,3,0.289423,0.726753,0.087925,0.610754,-3.145632e-16,-0.959919,False,-1.099000,-0.703919,-0.855982,False,0
5,Abia,6,0.797064,3,0.277903,0.726753,0.087925,0.799669,-3.145632e-16,-0.959919,False,-0.363000,0.449088,-0.855982,False,0
6,Abia,7,0.796211,3,0.301968,0.726753,0.087925,0.789975,-3.145632e-16,-0.959919,False,-0.521000,0.201567,-0.855982,False,0
7,Abia,8,0.800370,3,0.246360,0.726753,0.087925,0.837270,-3.145632e-16,-0.959919,False,-1.828667,-1.847004,-0.855982,True,0
8,Abia,9,0.811505,3,0.254307,0.726753,0.087925,0.963916,-3.145632e-16,-0.959919,False,-0.670667,-0.032898,-0.855982,False,0
9,Abia,10,0.794662,3,0.313025,0.726753,0.087925,0.772354,-3.145632e-16,-0.959919,False,-1.220333,-0.893998,-0.855982,True,0
10,Abia,11,0.726370,3,0.295682,0.726753,0.087925,-0.004356,-3.145632e-16,-0.959919,False,-0.653333,-0.005744,-0.855982,False,0
11,Abia,12,0.633201,3,0.381811,0.726753,0.087925,-1.064004,-3.145632e-16,-0.959919,True,-0.180333,0.735251,-0.855982,False,0
12,Abuja,1,0.317709,3,0.272305,0.533885,0.171904,-1.257538,-1.295260e-16,-1.113462,True,-0.159333,0.266387,-0.741501,False,0
13,Abuja,2,0.292107,3,0.288947,0.533885,0.171904,-1.406470,-1.295260e-16,-1.113462,True,0.666667,1.887275,-0.741501,False,0
14,Abuja,3,0.323778,2,0.312745,0.533885,0.171904,-1.222234,-1.295260e-16,-1.113462,True,0.047167,0.671609,-0.741501,False,0
15,Abuja,4,0.418740,3,0.261846,0.533885,0.171904,-0.669818,-1.295260e-16,-1.113462,False,-0.276583,0.036303,-0.741501,False,0
16,Abuja,5,0.554993,3,0.244790,0.533885,0.171904,0.122789,-1.295260e-16,-1.113462,False,-0.688167,-0.771361,-0.741501,True,0
17,Abuja,6,0.669883,3,0.301232,0.533885,0.171904,0.791128,-1.295260e-16,-1.113462,False,-0.418667,-0.242512,-0.741501,False,0
18,Abuja,7,0.720420,3,0.321530,0.533885,0.171904,1.085111,-1.295260e-16,-1.113462,False,-0.612083,-0.622060,-0.741501,False,0
19,Abuja,8,0.727833,3,0.231547,0.533885,0.171904,1.128236,-1.295260e-16,-1.113462,False,-0.963500,-1.311657,-0.741501,True,0

In [287]:
panel_true = panel[panel["lean_risk"] == 1] 
panel_true.head(50)

,NAME_1,month,ndvi_mean,n_obs,inadequate,mean_admin,std_admin,ndvi_anomaly,mean_anomaly_admin,ndvi_q20_threshold,ndvi_low_q20,spi_mean,spi_anomaly,spi_q20_threshold,spi_low_q20,lean_risk
1,Abia,2,0.597959,3,0.409660,0.726753,0.087925,-1.464822,-3.145632e-16,-0.959919,True,-1.373667,-1.134208,-0.855982,True,1
25,Adamawa,2,0.265666,3,0.459378,0.444814,0.149927,-1.194901,-1.572816e-16,-1.022038,True,-1.111000,-1.965379,-0.777021,True,1
37,Akwa Ibom,2,0.613420,3,0.372335,0.726390,0.072456,-1.559155,-2.498002e-16,-0.884774,True,-0.770472,-0.568307,-0.552233,True,1
75,Borno,4,0.229505,3,0.530465,0.381199,0.151697,-0.999975,-9.251859e-18,-0.888941,True,-0.477429,-1.287778,-0.583687,True,1
85,Cross River,2,0.630823,3,0.353008,0.740000,0.070869,-1.540539,5.366078e-16,-0.897476,True,-1.038833,-1.001153,-0.542937,True,1
136,Jigawa,4,0.215138,3,0.500091,0.332157,0.119288,-0.980985,-2.544261e-16,-0.884110,True,-1.246389,-1.967701,-0.494398,True,1
160,Kano,4,0.209998,3,0.478991,0.356833,0.162562,-0.903259,8.326673e-17,-0.850629,True,-0.663000,-1.277509,-1.106474,True,1
172,Katsina,4,0.204218,3,0.514650,0.356279,0.156941,-0.968912,1.480297e-16,-0.873082,True,0.061167,-0.976974,-0.620527,True,1
207,Kwara,3,0.381185,2,0.365075,0.552560,0.154410,-1.109868,4.625929e-17,-1.047521,True,-0.630500,-1.053552,-0.738307,True,1
228,Lagos,12,0.543276,3,0.332052,0.604390,0.056953,-1.073048,-5.551115e-16,-0.964799,True,-0.170333,-0.703570,-0.658331,True,1
282,Sokoto,5,0.222824,3,0.486235,0.334998,0.123221,-0.910346,-1.665335e-16,-0.878253,True,-0.209083,-1.268273,-1.139747,True,1
305,Yobe,4,0.204561,3,0.556931,0.310530,0.112968,-0.938041,5.088522e-17,-0.839356,True,-0.469667,-1.282471,-1.008791,True,1

In [288]:
months_lean = sorted(panel.loc[panel["lean_risk"] == 1, "month"].unique())
months_lean

[np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(12)]

In [289]:
month_counts = (panel.loc[panel["lean_risk"] == 1]#combien d'états touchés par mois
                .groupby("month")["NAME_1"]
                .nunique()
                .sort_index())
month_counts

month
2     4
3     1
4     5
5     1
12    1
Name: NAME_1, dtype: int64

In [290]:
panel2 = ndvi_monthly.merge(
    spi_monthly2[["NAME_1","month","spi_mean","spi_anomaly","spi_q80_threshold","spi_high_q80"]],
    on=["NAME_1","month"],
    how="left"
)

panel2.head(20)

,NAME_1,month,ndvi_mean,n_obs,inadequate,mean_admin,std_admin,ndvi_anomaly,mean_anomaly_admin,ndvi_q20_threshold,ndvi_low_q20,spi_mean,spi_anomaly,spi_q80_threshold,spi_high_q80
0,Abia,1,0.561547,3,0.357967,0.726753,0.087925,-1.878941,-3.145632e-16,-0.959919,True,-0.329000,0.502352,0.688671,False
1,Abia,2,0.597959,3,0.409660,0.726753,0.087925,-1.464822,-3.145632e-16,-0.959919,True,-1.373667,-1.134208,0.688671,False
2,Abia,3,0.678959,2,0.315020,0.726753,0.087925,-0.543580,-3.145632e-16,-0.959919,False,-0.002333,1.014103,0.688671,True
3,Abia,4,0.742734,3,0.346308,0.726753,0.087925,0.181765,-3.145632e-16,-0.959919,False,0.445333,1.715411,0.688671,True
4,Abia,5,0.780453,3,0.289423,0.726753,0.087925,0.610754,-3.145632e-16,-0.959919,False,-1.099000,-0.703919,0.688671,False
5,Abia,6,0.797064,3,0.277903,0.726753,0.087925,0.799669,-3.145632e-16,-0.959919,False,-0.363000,0.449088,0.688671,False
6,Abia,7,0.796211,3,0.301968,0.726753,0.087925,0.789975,-3.145632e-16,-0.959919,False,-0.521000,0.201567,0.688671,False
7,Abia,8,0.800370,3,0.246360,0.726753,0.087925,0.837270,-3.145632e-16,-0.959919,False,-1.828667,-1.847004,0.688671,False
8,Abia,9,0.811505,3,0.254307,0.726753,0.087925,0.963916,-3.145632e-16,-0.959919,False,-0.670667,-0.032898,0.688671,False
9,Abia,10,0.794662,3,0.313025,0.726753,0.087925,0.772354,-3.145632e-16,-0.959919,False,-1.220333,-0.893998,0.688671,False
10,Abia,11,0.726370,3,0.295682,0.726753,0.087925,-0.004356,-3.145632e-16,-0.959919,False,-0.653333,-0.005744,0.688671,False
11,Abia,12,0.633201,3,0.381811,0.726753,0.087925,-1.064004,-3.145632e-16,-0.959919,True,-0.180333,0.735251,0.688671,True
12,Abuja,1,0.317709,3,0.272305,0.533885,0.171904,-1.257538,-1.295260e-16,-1.113462,True,-0.159333,0.266387,0.670726,False
13,Abuja,2,0.292107,3,0.288947,0.533885,0.171904,-1.406470,-1.295260e-16,-1.113462,True,0.666667,1.887275,0.670726,True
14,Abuja,3,0.323778,2,0.312745,0.533885,0.171904,-1.222234,-1.295260e-16,-1.113462,True,0.047167,0.671609,0.670726,True
15,Abuja,4,0.418740,3,0.261846,0.533885,0.171904,-0.669818,-1.295260e-16,-1.113462,False,-0.276583,0.036303,0.670726,False
16,Abuja,5,0.554993,3,0.244790,0.533885,0.171904,0.122789,-1.295260e-16,-1.113462,False,-0.688167,-0.771361,0.670726,False
17,Abuja,6,0.669883,3,0.301232,0.533885,0.171904,0.791128,-1.295260e-16,-1.113462,False,-0.418667,-0.242512,0.670726,False
18,Abuja,7,0.720420,3,0.321530,0.533885,0.171904,1.085111,-1.295260e-16,-1.113462,False,-0.612083,-0.622060,0.670726,False
19,Abuja,8,0.727833,3,0.231547,0.533885,0.171904,1.128236,-1.295260e-16,-1.113462,False,-0.963500,-1.311657,0.670726,False

In [291]:
panel2["lean_rain_high_veg_low"] = (panel2["spi_high_q80"] & panel2["ndvi_low_q20"]).astype(int)

panel2.head(20)

,NAME_1,month,ndvi_mean,n_obs,inadequate,mean_admin,std_admin,ndvi_anomaly,mean_anomaly_admin,ndvi_q20_threshold,ndvi_low_q20,spi_mean,spi_anomaly,spi_q80_threshold,spi_high_q80,lean_rain_high_veg_low
0,Abia,1,0.561547,3,0.357967,0.726753,0.087925,-1.878941,-3.145632e-16,-0.959919,True,-0.329000,0.502352,0.688671,False,0
1,Abia,2,0.597959,3,0.409660,0.726753,0.087925,-1.464822,-3.145632e-16,-0.959919,True,-1.373667,-1.134208,0.688671,False,0
2,Abia,3,0.678959,2,0.315020,0.726753,0.087925,-0.543580,-3.145632e-16,-0.959919,False,-0.002333,1.014103,0.688671,True,0
3,Abia,4,0.742734,3,0.346308,0.726753,0.087925,0.181765,-3.145632e-16,-0.959919,False,0.445333,1.715411,0.688671,True,0
4,Abia,5,0.780453,3,0.289423,0.726753,0.087925,0.610754,-3.145632e-16,-0.959919,False,-1.099000,-0.703919,0.688671,False,0
5,Abia,6,0.797064,3,0.277903,0.726753,0.087925,0.799669,-3.145632e-16,-0.959919,False,-0.363000,0.449088,0.688671,False,0
6,Abia,7,0.796211,3,0.301968,0.726753,0.087925,0.789975,-3.145632e-16,-0.959919,False,-0.521000,0.201567,0.688671,False,0
7,Abia,8,0.800370,3,0.246360,0.726753,0.087925,0.837270,-3.145632e-16,-0.959919,False,-1.828667,-1.847004,0.688671,False,0
8,Abia,9,0.811505,3,0.254307,0.726753,0.087925,0.963916,-3.145632e-16,-0.959919,False,-0.670667,-0.032898,0.688671,False,0
9,Abia,10,0.794662,3,0.313025,0.726753,0.087925,0.772354,-3.145632e-16,-0.959919,False,-1.220333,-0.893998,0.688671,False,0
10,Abia,11,0.726370,3,0.295682,0.726753,0.087925,-0.004356,-3.145632e-16,-0.959919,False,-0.653333,-0.005744,0.688671,False,0
11,Abia,12,0.633201,3,0.381811,0.726753,0.087925,-1.064004,-3.145632e-16,-0.959919,True,-0.180333,0.735251,0.688671,True,1
12,Abuja,1,0.317709,3,0.272305,0.533885,0.171904,-1.257538,-1.295260e-16,-1.113462,True,-0.159333,0.266387,0.670726,False,0
13,Abuja,2,0.292107,3,0.288947,0.533885,0.171904,-1.406470,-1.295260e-16,-1.113462,True,0.666667,1.887275,0.670726,True,1
14,Abuja,3,0.323778,2,0.312745,0.533885,0.171904,-1.222234,-1.295260e-16,-1.113462,True,0.047167,0.671609,0.670726,True,1
15,Abuja,4,0.418740,3,0.261846,0.533885,0.171904,-0.669818,-1.295260e-16,-1.113462,False,-0.276583,0.036303,0.670726,False,0
16,Abuja,5,0.554993,3,0.244790,0.533885,0.171904,0.122789,-1.295260e-16,-1.113462,False,-0.688167,-0.771361,0.670726,False,0
17,Abuja,6,0.669883,3,0.301232,0.533885,0.171904,0.791128,-1.295260e-16,-1.113462,False,-0.418667,-0.242512,0.670726,False,0
18,Abuja,7,0.720420,3,0.321530,0.533885,0.171904,1.085111,-1.295260e-16,-1.113462,False,-0.612083,-0.622060,0.670726,False,0
19,Abuja,8,0.727833,3,0.231547,0.533885,0.171904,1.128236,-1.295260e-16,-1.113462,False,-0.963500,-1.311657,0.670726,False,0

In [292]:
panel_true2 = panel2[panel2["lean_rain_high_veg_low"] == 1] 
panel_true2.head(50)

,NAME_1,month,ndvi_mean,n_obs,inadequate,mean_admin,std_admin,ndvi_anomaly,mean_anomaly_admin,ndvi_q20_threshold,ndvi_low_q20,spi_mean,spi_anomaly,spi_q80_threshold,spi_high_q80,lean_rain_high_veg_low
11,Abia,12,0.633201,3,0.381811,0.726753,0.087925,-1.064004,-3.145632e-16,-0.959919,True,-0.180333,0.735251,0.688671,True,1
13,Abuja,2,0.292107,3,0.288947,0.533885,0.171904,-1.406470,-1.295260e-16,-1.113462,True,0.666667,1.887275,0.670726,True,1
14,Abuja,3,0.323778,2,0.312745,0.533885,0.171904,-1.222234,-1.295260e-16,-1.113462,True,0.047167,0.671609,0.670726,True,1
47,Akwa Ibom,12,0.657028,3,0.362620,0.726390,0.072456,-0.957296,-2.498002e-16,-0.884774,True,0.011083,0.766594,0.743365,True,1
60,Benue,1,0.368242,3,0.454139,0.573351,0.143145,-1.432875,1.480297e-16,-1.081543,True,0.029111,0.916865,0.827293,True,1
84,Cross River,1,0.614244,3,0.349539,0.740000,0.070869,-1.774477,5.366078e-16,-0.897476,True,-0.115500,0.754635,0.695496,True,1
95,Cross River,12,0.673410,3,0.307047,0.740000,0.070869,-0.939623,5.366078e-16,-0.897476,True,0.220833,1.394198,0.695496,True,1
108,Edo,12,0.626242,3,0.382662,0.722802,0.096366,-1.002014,4.810966e-16,-0.938578,True,-0.107833,1.042474,0.820128,True,1
120,Enugu,12,0.559134,3,0.390997,0.665063,0.111531,-0.949765,6.198745e-16,-0.936515,True,0.024667,1.078121,0.909546,True,1
135,Jigawa,3,0.224857,2,0.608522,0.332157,0.119288,-0.899511,-2.544261e-16,-0.884110,True,2.087833,1.922765,0.474847,True,1
146,Kaduna,2,0.297888,3,0.592317,0.488217,0.160401,-1.186580,2.498002e-16,-1.021008,True,0.840000,1.763696,0.843071,True,1
147,Kaduna,3,0.314601,2,0.539224,0.488217,0.160401,-1.082388,2.498002e-16,-1.021008,True,0.325750,0.935214,0.843071,True,1
159,Kano,3,0.211279,2,0.620972,0.356833,0.162562,-0.895379,8.326673e-17,-0.850629,True,1.123833,0.944573,0.826267,True,1
194,Kogi,2,0.427972,3,0.406327,0.623552,0.128906,-1.517230,-1.480297e-16,-0.997514,True,0.051111,0.895342,0.870645,True,1
218,Lagos,2,0.520561,3,0.271222,0.604390,0.056953,-1.471889,-5.551115e-16,-0.964799,True,0.474667,0.626797,0.588570,True,1
230,Niger,2,0.271473,3,0.585102,0.472800,0.156492,-1.286498,2.312965e-16,-1.081913,True,0.650095,1.206919,1.046247,True,1
241,Ogun,1,0.529200,3,0.322895,0.706991,0.094026,-1.890868,4.810966e-16,-0.859664,True,0.177000,0.659296,0.623574,True,1
266,Rivers,1,0.554364,3,0.373230,0.693123,0.069578,-1.994280,6.476301e-16,-0.963694,True,-0.289500,0.496282,0.443072,True,1
304,Yobe,3,0.214668,2,0.507028,0.310530,0.112968,-0.848577,5.088522e-17,-0.839356,True,0.923667,0.802807,0.795923,True,1
315,Zamfara,2,0.251404,3,0.716967,0.417055,0.163283,-1.014503,-3.700743e-17,-0.956721,True,1.214667,0.831058,0.776571,True,1

In [293]:
months_lean2 = sorted(panel2.loc[panel2["lean_rain_high_veg_low"] == 1, "month"].unique())
months_lean2

[np.int64(1), np.int64(2), np.int64(3), np.int64(12)]